### ISSUE TITLE
Redo feed page content and styling

### ISSUE THREAD

**Issue by paulcretu** [orcasound/orcasite#194]
- todo: update this issue with screenshots of designs
```[tasklist]
### Tasks
- [x] Scott: Add "Status update" to each feed's HTML
- [x] Scott: Move links to orcasound.net/portfolio to bottom of HTML block for all feeds
- [x] Scott: Add WDFW credit where appropriate
- [x] Paul: Remove links to old Google map screenshots for all feeds that still show the image after the HTML block
- [x] Scott: Edit all feed content and ask hosts for feedback
- [ ] Scott: Make final edits based on host feedback
```

**Comment by scottveirs** [comment]
@paulcretu I'm working my way through the feed description content and should be done tomorrow. BTW -- I found I could add a `strong` element for the status update and like the way it renders, but LMK if you'd rather I not add such HTML bits!

<img width="585" alt="Screenshot 2023-10-18 at 2 21 30 PM" src="https://github.com/orcasound/orcasite/assets/14044595/ba7cd888-6de1-4fa7-801a-66479cbca18c">

**Comment by scottveirs** [comment]
Hey @paulcretu -- I've checked boxes at top of this card for WDFW credit and notifying hosts. I've queried all host orgs about their feed content and 2/7 have responded. 

- North San Juan Channel folks are happy.
- I'll implement a photo change requested by Sunset Bay hosts today.

**Comment by paulcretu** [comment]
> BTW -- I found I could add a `strong` element for the status update and like the way it renders, but LMK if you'd rather I not add such HTML bits!

Totally fine for now—ideally we'd have some CMS/rich text editing option but as a workaround until then this is fine. We'll just need to be mindful of the HTML we use since it gets inserted directly into the page.

**Comment by paulcretu** [comment]
Closing this as the dev work is done for now (though we could do a better design pass soon)
