### ISSUE TITLE
Polish landing page

### ISSUE THREAD

**Issue by paulcretu** [orcasound/orcasite#236]
- [x] Re-add learning section
- [x] Add an image or something to make mobile look less austere (ideally snap point to show map)
- [x] Edit copy
```[tasklist]
### Tasks
- [x] Move Learn and Listen buttons above fold (either under title, or after first paragraph)
- [x] On Learn page, change text slightly to "Here are some samples of calls, echolocation clicks, and whistles that are made by southern salmon-seeking killer whales:"
- [x] On landing page, make two minor changes:  Change "and their environment." to "and study their acoustic environment." and change "algorithms" to "AI"
```

**Comment by scottveirs** [comment]
@paulcretu  IMHO, if you move buttons up higher on the landing page it won't look to austere on mobile.

In terms of adjusting copy on the landing page, I think it reads fine, but might suggest these two minor changes:

1. Change "and their environment." to "and study their acoustic environment."
2. Change "algorithms" to "AI"

**Comment by scottveirs** [comment]
Looking good (not austere!) on iOS/Chrome @paulcretu !


![Image](https://github.com/orcasound/orcasite/assets/14044595/5bbb0033-f9ae-4248-9e65-2846f5344a7b)

**Comment by scottveirs** [comment]
Haha, this morning I read the issue title as "Polish" as in Poland! It was exciting to briefly think we were already facing the challenge of internationalizing Orcasound for each non-English-speaking country...
