### ISSUE TITLE
v3 post-deployment checklist

### ISSUE THREAD

**Issue by skanderm** [orcasound/orcasite#270]
- [ ] ~~Upgrade dyno memory to above 512mb (1gb?)~~ [Skipping for now until it becomes a problem
- [x] Upgrade heroku stack, elixir buildpacks
- [x] Update env variables from beta
- [x] Export mailing list, import as subscribers
- [x] Update notification subscription script endpoint to prod
- [x] Verify GA4 integration
- [x] Run data migrations: Feeds, detections, candidates; Populate feed intro; Detection categories; Feed image urls
- [x] Create admin accounts
- [x] Export and reimport feeds, detections, candidates, subscribers from beta to prod.
- [x] Request the ML team to switch their JSON API endpoint config: https://github.com/orcasound/aifororcas-livesystem/issues/128
- [x] Upgrade Redis once TLS settings have been tested in dev
