### ISSUE TITLE
v3 launch

### ISSUE THREAD

**Issue by paulcretu** [orcasound/orcasite#313]
```[tasklist]
### Tasks
- [ ] https://github.com/orcasound/orcasite/issues/264
- [ ] https://github.com/orcasound/orcasite/issues/198
- [ ] https://github.com/orcasound/orcasite/issues/199
- [ ] https://github.com/orcasound/orcasite/issues/169
- [ ] https://github.com/orcasound/orcasite/issues/82
- [ ] https://github.com/orcasound/orcasite/issues/226
- [ ] https://github.com/orcasound/orcasite/issues/220
- [ ] https://github.com/orcasound/orcasite/issues/314
- [ ] https://github.com/orcasound/orcasite/issues/270
- [ ] https://github.com/orcasound/orcasite/issues/247
- [ ] https://github.com/orcasound/orcasite/issues/231
- [ ] https://github.com/orcasound/orcasite/issues/229
- [ ] https://github.com/orcasound/orcasite/issues/233
- [ ] https://github.com/orcasound/orcasite/issues/184
- [ ] https://github.com/orcasound/orcasite/issues/225
- [ ] https://github.com/orcasound/orcasite/issues/212
- [ ] https://github.com/orcasound/orcasite/issues/196
- [ ] https://github.com/orcasound/orcasite/issues/236
- [ ] https://github.com/orcasound/orcasite/issues/250
- [ ] https://github.com/orcasound/orcasite/issues/315
- [ ] https://github.com/orcasound/orcasite/issues/193
- [ ] https://github.com/orcasound/orcasite/issues/192
- [ ] https://github.com/orcasound/orcasite/issues/191
- [ ] https://github.com/orcasound/orcasite/issues/195
- [ ] https://github.com/orcasound/orcasite/issues/316
- [ ] https://github.com/orcasound/orcasite/issues/223
- [ ] https://github.com/orcasound/orcasite/issues/112
- [ ] https://github.com/orcasound/orcasite/issues/224
- [ ] https://github.com/orcasound/orcasite/issues/111
```
