### ISSUE TITLE
Grayed out play button is confusing to users

### ISSUE THREAD

**Issue by Filadora** [orcasound/orcasite#334]
Users were confused with the play button. It is disabled before the user chooses a hydrophone and after the hydrophone is chosen there is a need to click on it. This two-step flow confused users and made them think that something was not working properly (either hydrophones or a play button).

Possibly that is a bug (according to Paul).

<img width="890" alt="Screenshot 2024-02-06 at 4 13 37 PM" src="https://github.com/orcasound/orcasite/assets/116315084/3c4282f5-a740-41ff-b03e-3e9bbec8d955">

```[tasklist]
### Tasks
- [ ] https://github.com/orcasound/orcasite/issues/232
- [ ] https://github.com/orcasound/orcasite/issues/641
- [ ] https://github.com/orcasound/orcasite/issues/662
- [ ] https://github.com/orcasound/orcasite/issues/197
```

**Comment by paulcretu** [comment]
I've tried to reproduce this on desktop and mobile (Chrome and Firefox), and I can't get the exact same behavior. I can confirm that the play button is grayed out before a location is selected (which is expected), but my audio always seems to autoplay once I select a location.

I agree that the grayed out play button might be confusing. My thought was to remove the bottom player bar completely when nothing is selected (see #232), but happy to discuss other solutions.

**Comment by adrmac** [comment]
I agree this issue is a priority. In analytics, we can see a lot of drop off (70%) with new users coming to the home screen but never starting the player. Going from the "Listen Live" call to action on the orcahome site, there are 3 clicks required to get to an audio stream:
1. Listen Live
2. Home: Select a hydrophone 
3. Listen: Select a hydrophone 
4. Hydrophone auto-starts after selection

I believe users are dropping off on step 2. Here are three ideas to resolve this:
1. Hide player bar on the Home screen (Paul's proposal)
2. Link the Listen Live button directly to the Listen screen (simplest, maybe good to test), and/or consolidate Home and Listen into one screen
3. Have the live.orcasound.net URL default to Orcasound Lab for new users, or most recently opened player for returning users (no autoplay)

How do we know if we are successful in resolving this? 
We should see the number of player starts rise as a % of site visits.
