### ISSUE TITLE
Tracking dev issues for "thank you for submitting" modal

### ISSUE THREAD

**Issue by mrose15** [orcasound/orcasite#361]
Original ticket: #240 
```[tasklist]
### Tasks
- [ ] https://github.com/orcasound/orcasite/issues/362
- [ ] https://github.com/orcasound/orcasite/issues/363
- [ ] https://github.com/orcasound/orcasite/issues/364
```

**Comment by mrose15** [comment]
See Figma file here: https://www.figma.com/file/41JuvNkXJhTUob8HMsJiNC/Orcasite%3A-design-updates?type=design&node-id=1228-8644&mode=design&t=MdqnMevD5akve9Mx-0
