### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by adrmac** [orcasound/orcasite#648]
```[tasklist]
### Tasks
- [ ] https://github.com/orcasound/orcasite/issues/230
- [ ] https://github.com/orcasound/orcasite/issues/331
- [ ] https://github.com/orcasound/orcasite/issues/28
- [ ] https://github.com/orcasound/orcasite/issues/97
- [ ] https://github.com/orcasound/orcasite/issues/96
- [ ] https://github.com/orcasound/orcasite/issues/334
- [ ] https://github.com/orcasound/orcasite/issues/665
```
